"""Initial migration

Revision ID: 2a3542d82c51
Revises: 
Create Date: 2026-02-02 15:16:08.959256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a3542d82c51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='OAuth 제공자 (kakao, google, naver)'),
    sa.Column('provider_id', sa.String(length=100), nullable=False, comment='OAuth 제공자별 고유 ID'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='이메일'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='이름'),
    sa.Column('nickname', sa.String(length=100), nullable=True, comment='닉네임'),
    sa.Column('profile_image', sa.String(length=500), nullable=True, comment='프로필 이미지 URL'),
    sa.Column('role', sa.String(length=20), nullable=True, comment='사용자 권한'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='OAuth 사용자 정보'
    )
    
    # 테이블/인덱스 존재 여부 확인 후 삭제
    conn = op.get_bind()
    
    # playing_with_neon 테이블 삭제
    result = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'playing_with_neon'
        );
    """))
    if result.scalar():
        op.drop_table('playing_with_neon')
    
    # refresh_tokens 테이블 및 인덱스 삭제
    result = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'refresh_tokens'
        );
    """))
    if result.scalar():
        # 인덱스 삭제
        result = conn.execute(sa.text("""
            SELECT EXISTS (
                SELECT FROM information_schema.indexes 
                WHERE table_schema = 'public' 
                AND table_name = 'refresh_tokens' 
                AND index_name = 'idx_expires_at'
            );
        """))
        if result.scalar():
            op.drop_index(op.f('idx_expires_at'), table_name='refresh_tokens')
        
        result = conn.execute(sa.text("""
            SELECT EXISTS (
                SELECT FROM information_schema.indexes 
                WHERE table_schema = 'public' 
                AND table_name = 'refresh_tokens' 
                AND index_name = 'idx_provider_user'
            );
        """))
        if result.scalar():
            op.drop_index(op.f('idx_provider_user'), table_name='refresh_tokens')
        
        op.drop_table('refresh_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey'))
    )
    op.create_index(op.f('idx_provider_user'), 'refresh_tokens', ['provider', 'user_id'], unique=False)
    op.create_index(op.f('idx_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    
    # users 테이블이 존재하는지 확인 후 삭제
    conn = op.get_bind()
    result = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'users'
        );
    """))
    table_exists = result.scalar()
    
    if table_exists:
        op.drop_table('users')
    # ### end Alembic commands ###

