"""add user_competency and user_roadmap_status tables

Revision ID: 553c40c8a4c7
Revises: a8e3cc9dcf27
Create Date: 2026-02-04 16:29:21.584893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '553c40c8a4c7'
down_revision: Union[str, None] = 'a8e3cc9dcf27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_competency',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='고유 ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='사용자 식별자'),
    sa.Column('skill_name', sa.String(length=100), nullable=False, comment='스킬명 (Python, 기획 등)'),
    sa.Column('skill_level', sa.Integer(), nullable=False, comment='숙련도 (1~5) - 역량 갭(Gap) 분석'),
    sa.Column('is_certified', sa.Boolean(), nullable=False, comment='자격/경험 여부 - 데이터 신뢰도 보정'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시간'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시간'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='사용자 역량 정보'
    )
    op.create_index('idx_user_competency_user_id', 'user_competency', ['user_id'], unique=False)
    op.create_index('idx_user_competency_user_skill', 'user_competency', ['user_id', 'skill_name'], unique=False)
    op.create_table('user_roadmap_status',
    sa.Column('roadmap_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='로드맵 고유 ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='사용자 식별자'),
    sa.Column('target_trend_id', sa.Integer(), nullable=True, comment='목표로 삼은 트렌드 ID - 세상의 요구 지도와 연결 (trends 테이블 생성 후 ForeignKey 추가 예정)'),
    sa.Column('progress_rate', sa.Float(), nullable=False, comment='학습 진척도 (0~100) - AI 코치의 피드백 근거'),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='최종 활동 시간 - 리마인드 알림 시점 계산'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시간'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시간'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('roadmap_id'),
    comment='사용자 로드맵 진행 상태'
    )
    op.create_index('idx_user_roadmap_last_active', 'user_roadmap_status', ['last_active_at'], unique=False)
    op.create_index('idx_user_roadmap_user_id', 'user_roadmap_status', ['user_id'], unique=False)
    op.create_index('idx_user_roadmap_user_trend', 'user_roadmap_status', ['user_id', 'target_trend_id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               comment='사용자 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시간',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_users_provider_provider_id', 'users', ['provider', 'provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_provider_provider_id', table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성 시간',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='사용자 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('idx_user_roadmap_user_trend', table_name='user_roadmap_status')
    op.drop_index('idx_user_roadmap_user_id', table_name='user_roadmap_status')
    op.drop_index('idx_user_roadmap_last_active', table_name='user_roadmap_status')
    op.drop_table('user_roadmap_status')
    op.drop_index('idx_user_competency_user_skill', table_name='user_competency')
    op.drop_index('idx_user_competency_user_id', table_name='user_competency')
    op.drop_table('user_competency')
    # ### end Alembic commands ###

