"""add coach_sessions and messages

Revision ID: 26149c601ff7
Revises: b4cb00cc6a07
Create Date: 2026-07-02 00:02:54.404241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26149c601ff7'
down_revision: Union[str, None] = 'b4cb00cc6a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='active', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_coach_session_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='코치 대화 세션 — 명시적 세션·롤링 요약·추출 표시'
    )
    op.create_index('ix_coach_sessions_user', 'coach_sessions', ['user_id'], unique=False)
    op.create_table('coach_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['coach_sessions.id'], name='fk_coach_message_session', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='코치 대화 메시지 — 세션별 턴(user/assistant)'
    )
    op.create_index('ix_coach_messages_session', 'coach_messages', ['session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_coach_messages_session', table_name='coach_messages')
    op.drop_table('coach_messages')
    op.drop_index('ix_coach_sessions_user', table_name='coach_sessions')
    op.drop_table('coach_sessions')
    # ### end Alembic commands ###
