"""Add pref_domain_json, value_growth, value_stability, value_impact columns

Revision ID: a8e3cc9dcf27
Revises: add_age_field
Create Date: 2026-02-03 15:50:26.088454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8e3cc9dcf27'
down_revision: Union[str, None] = 'add_age_field'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pref_domain_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='선호 도메인 JSON'))
    op.add_column('users', sa.Column('value_growth', sa.Float(), nullable=True, comment='성장 가치'))
    op.add_column('users', sa.Column('value_stability', sa.Float(), nullable=True, comment='안정성 가치'))
    op.add_column('users', sa.Column('value_impact', sa.Float(), nullable=True, comment='영향력 가치'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'value_impact')
    op.drop_column('users', 'value_stability')
    op.drop_column('users', 'value_growth')
    op.drop_column('users', 'pref_domain_json')
    # ### end Alembic commands ###

