"""Add age field to users table

Revision ID: add_age_field
Revises: 2a3542d82c51
Create Date: 2026-02-02 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'add_age_field'
down_revision: Union[str, None] = '2a3542d82c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True, comment='나이'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 테이블이 존재하는지 확인 후 컬럼 제거
    conn = op.get_bind()
    result = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'users'
        );
    """))
    table_exists = result.scalar()
    
    if table_exists:
        # age 컬럼이 존재하는지 확인
        result = conn.execute(sa.text("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = 'users' 
                AND column_name = 'age'
            );
        """))
        column_exists = result.scalar()
        
        if column_exists:
            op.drop_column('users', 'age')
    # ### end Alembic commands ###

