"""enhance_raw_economic_data_schema

Revision ID: fa5b6fba5c4c
Revises: c7e9b2a1f4d0
Create Date: 2026-05-11 03:05:43.245338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa5b6fba5c4c'
down_revision: Union[str, None] = 'c7e9b2a1f4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_economic_data', sa.Column('raw_title', sa.String(length=500), nullable=False, comment='공시 제목, 뉴스 헤드라인'))
    op.add_column('raw_economic_data', sa.Column('investor_name', sa.String(length=255), nullable=True, comment='투자 주체'))
    op.add_column('raw_economic_data', sa.Column('currency', sa.String(length=10), server_default='KRW', nullable=False, comment='통화'))
    op.add_column('raw_economic_data', sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='원천 데이터 확장 정보'))
    op.add_column('raw_economic_data', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='실제 공시일/기사 발행일'))
    op.alter_column('raw_economic_data', 'source_type',
               existing_type=sa.VARCHAR(length=50),
               comment='DART_API, VC_NEWS 등',
               existing_comment='DART, WOWTALE 등',
               existing_nullable=False)
    op.alter_column('raw_economic_data', 'source_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_comment='원문/출처 URL',
               existing_nullable=True)
    op.alter_column('raw_economic_data', 'target_company_or_fund',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_comment='투자 대상 기업·펀드',
               existing_nullable=True)
    op.drop_index(op.f('ix_raw_economic_source_type_url'), table_name='raw_economic_data')
    op.create_table_comment(
        'raw_economic_data',
        'Bronze — 경제·투자·예산 등 자본 흐름 원천',
        existing_comment='Bronze — 경제·투자 원천',
        schema=None
    )
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='활성/휴면 상태',
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='활성/휴면 상태',
               existing_server_default=sa.text('true'))
    op.create_table_comment(
        'raw_economic_data',
        'Bronze — 경제·투자 원천',
        existing_comment='Bronze — 경제·투자·예산 등 자본 흐름 원천',
        schema=None
    )
    op.create_index(op.f('ix_raw_economic_source_type_url'), 'raw_economic_data', ['source_type', 'source_url'], unique=False)
    op.alter_column('raw_economic_data', 'target_company_or_fund',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_comment='투자 대상 기업·펀드',
               existing_nullable=True)
    op.alter_column('raw_economic_data', 'source_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_comment='원문/출처 URL',
               existing_nullable=True)
    op.alter_column('raw_economic_data', 'source_type',
               existing_type=sa.VARCHAR(length=50),
               comment='DART, WOWTALE 등',
               existing_comment='DART_API, VC_NEWS 등',
               existing_nullable=False)
    op.drop_column('raw_economic_data', 'published_at')
    op.drop_column('raw_economic_data', 'raw_metadata')
    op.drop_column('raw_economic_data', 'currency')
    op.drop_column('raw_economic_data', 'investor_name')
    op.drop_column('raw_economic_data', 'raw_title')
    # ### end Alembic commands ###

